"use client";
import { useEffect,useState } from "react";
import Shell from "@/components/layout/Shell";
import { Plus, Wrench, CheckCircle2, X, RefreshCw } from "lucide-react";
import { formatCurrency } from "@/lib/validation";
export default function OrdensServicoPage(){
 const [ordens,setOrdens]=useState<any[]>([]); const [flats,setFlats]=useState<any[]>([]); const [open,setOpen]=useState(false); const [form,setForm]=useState<any>({titulo:"",descricao:"",flatId:"",prioridade:"MEDIA",categoria:"MANUTENCAO",valorEstimado:"",prazo:""}); const [loading,setLoading]=useState(true);
 const load=()=>Promise.all([fetch("/api/ordens-servico").then(r=>r.json()),fetch("/api/flats").then(r=>r.json())]).then(([a,b])=>{setOrdens(a.ordens||[]);setFlats(b.flats||[])}).finally(()=>setLoading(false));
 useEffect(()=>{load()},[]);
 const save=async(e:any)=>{e.preventDefault();await fetch("/api/ordens-servico",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setOpen(false);setForm({titulo:"",descricao:"",flatId:"",prioridade:"MEDIA",categoria:"MANUTENCAO",valorEstimado:"",prazo:""});load()};
 const status=async(o:any,s:string)=>{await fetch("/api/ordens-servico",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:o.id,status:s})});load()};
 return <Shell><div className="space-y-6"><div className="flex justify-between border-b border-slate-200 dark:border-slate-800 pb-4"><div><h1 className="text-lg font-bold">Ordens de Serviço</h1><p className="text-xs text-slate-500">Manutenção, limpeza, reparos e acompanhamento de execução.</p></div><button onClick={()=>setOpen(true)} className="px-4 py-2 rounded-xl bg-blue-600 text-white text-xs font-bold flex gap-2 items-center"><Plus className="w-4 h-4"/> Nova OS</button></div>
 <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">{loading?<p className="text-xs text-slate-500">Carregando...</p>:ordens.map(o=><div key={o.id} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-4"><div className="flex justify-between"><div><span className="text-[10px] text-blue-600 font-bold">{o.codigo}</span><h2 className="font-bold text-sm mt-1">{o.titulo}</h2></div><Wrench className="w-5 h-5 text-slate-400"/></div><p className="text-xs text-slate-500 mt-2">{o.descricao||"Sem descrição"}</p><div className="flex flex-wrap gap-2 mt-3 text-[10px]"><span className="px-2 py-1 rounded-lg bg-slate-100 dark:bg-slate-800">{o.prioridade}</span><span className="px-2 py-1 rounded-lg bg-blue-50 dark:bg-blue-950 text-blue-600">{o.status}</span>{o.flat&&<span className="px-2 py-1 rounded-lg bg-slate-100 dark:bg-slate-800">Flat {o.flat.numero}</span>}</div><div className="flex items-center justify-between mt-4"><span className="text-xs font-semibold">{formatCurrency(o.valorReal||o.valorEstimado||0)}</span><div className="flex gap-2">{o.status==="ABERTA"&&<button onClick={()=>status(o,"EM_EXECUCAO")} className="text-[10px] px-2 py-1 rounded-lg bg-blue-600 text-white">Iniciar</button>}{o.status==="EM_EXECUCAO"&&<button onClick={()=>status(o,"CONCLUIDA")} className="text-[10px] px-2 py-1 rounded-lg bg-emerald-600 text-white"><CheckCircle2 className="w-3 h-3 inline"/> Concluir</button>}</div></div></div>)}</div>
 {open&&<div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white dark:bg-slate-900 p-6 space-y-3"><div className="flex justify-between"><h2 className="font-bold">Nova Ordem de Serviço</h2><button type="button" onClick={()=>setOpen(false)}><X className="w-4 h-4"/></button></div><input required placeholder="Título" value={form.titulo} onChange={e=>setForm({...form,titulo:e.target.value})} className="w-full rounded-xl border p-3 text-xs bg-transparent"/><textarea placeholder="Descrição" value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})} className="w-full rounded-xl border p-3 text-xs bg-transparent"/><div className="grid grid-cols-2 gap-3"><select value={form.flatId} onChange={e=>setForm({...form,flatId:e.target.value})} className="rounded-xl border p-3 text-xs bg-transparent"><option value="">Imóvel</option>{flats.map(f=><option key={f.id} value={f.id}>{f.numero}</option>)}</select><select value={form.prioridade} onChange={e=>setForm({...form,prioridade:e.target.value})} className="rounded-xl border p-3 text-xs bg-transparent"><option>BAIXA</option><option>MEDIA</option><option>ALTA</option><option>URGENTE</option></select></div><input type="number" step="0.01" placeholder="Valor estimado" value={form.valorEstimado} onChange={e=>setForm({...form,valorEstimado:e.target.value})} className="w-full rounded-xl border p-3 text-xs bg-transparent"/><input type="date" value={form.prazo} onChange={e=>setForm({...form,prazo:e.target.value})} className="w-full rounded-xl border p-3 text-xs bg-transparent"/><button className="w-full rounded-xl bg-blue-600 text-white p-3 text-xs font-bold">Criar OS</button></form></div>}
 </div></Shell>
}
