"use client";

import React, { useEffect, useMemo, useState } from "react";
import Shell from "@/components/layout/Shell";
import { ArrowLeft, ArrowRight, CheckCircle2, FileText } from "lucide-react";

export default function NovoContratoWizard() {
  const [step,setStep]=useState(1); const [locatarios,setLocatarios]=useState<any[]>([]); const [flats,setFlats]=useState<any[]>([]); const [modelos,setModelos]=useState<any[]>([]);
  const [form,setForm]=useState({locatarioId:"",flatId:"",modeloContratoId:"",dataEmissao:new Date().toISOString().slice(0,10),tipoValidade:"MESES",validadeValor:"12",valorMensal:"",diaVencimento:"5",formaPagamento:"PIX",multaAtrasoPercentual:"2",jurosAtrasoPercentual:"1",valorCaucao:"0",caucaoParcelas:"0",multaRescisaoMeses:"3"});
  const [saving,setSaving]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{Promise.all([fetch("/api/locatarios").then(r=>r.json()),fetch("/api/flats").then(r=>r.json()),fetch("/api/modelos-contrato").then(r=>r.json())]).then(([a,b,c])=>{setLocatarios(a.locatarios||[]);setFlats((b.flats||[]).filter((x:any)=>x.status==="DISPONIVEL"));setModelos(c.modelos||[])}).catch(()=>setError("Não foi possível carregar os dados."))},[]);
  const selectedFlat=flats.find(x=>x.id===form.flatId); const selectedLoc=locatarios.find(x=>x.id===form.locatarioId); const model=modelos.find(x=>x.id===form.modeloContratoId);
  const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
  const submit=async()=>{setSaving(true);setError("");try{const res=await fetch("/api/contratos",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await res.json();if(!res.ok)throw new Error(d.error||"Erro ao emitir contrato");setDone(true);setTimeout(()=>window.location.href=`/contratos/${d.contrato.id}`,500)}catch(e:any){setError(e.message)}finally{setSaving(false)}};
  const dataFinal=useMemo(()=>{const d=new Date(form.dataEmissao);const n=Math.max(1,Number(form.validadeValor)||1);if(form.tipoValidade==="DIAS")d.setDate(d.getDate()+n);else d.setMonth(d.getMonth()+n);return d.toLocaleDateString("pt-BR")},[form]);
  return <Shell><div className="max-w-5xl mx-auto space-y-6">
    <div className="flex items-center gap-3"><button onClick={()=>window.location.href="/contratos"} className="p-2 rounded-xl border bg-white dark:bg-slate-900"><ArrowLeft className="w-4 h-4"/></button><div><p className="text-[10px] font-bold text-blue-600 uppercase">Fase 3</p><h1 className="text-xl font-extrabold">Assistente de emissão de contrato</h1><p className="text-xs text-slate-500">Preencha, revise e emita em etapas.</p></div></div>
    <div className="grid grid-cols-4 gap-2">{["Partes e imóvel","Vigência","Financeiro","Revisão"].map((x,i)=><div key={x} className={`p-3 rounded-xl text-xs font-bold ${step===i+1?"bg-blue-600 text-white":"bg-white dark:bg-slate-900 border"}`}>{i+1}. {x}</div>)}</div>
    {error&&<div className="p-3 rounded-xl bg-rose-50 text-rose-700 text-xs font-semibold">{error}</div>}
    <div className="bg-white dark:bg-slate-900 border rounded-2xl p-6 shadow-sm">
      {step===1&&<div className="grid md:grid-cols-2 gap-4"><label className="text-xs font-semibold">Locatário<select value={form.locatarioId} onChange={e=>set("locatarioId",e.target.value)} className="mt-1 w-full p-3 rounded-xl border bg-transparent"><option value="">Selecione</option>{locatarios.map(x=><option key={x.id} value={x.id}>{x.nome} • {x.cpf}</option>)}</select></label><label className="text-xs font-semibold">Imóvel<select value={form.flatId} onChange={e=>set("flatId",e.target.value)} className="mt-1 w-full p-3 rounded-xl border bg-transparent"><option value="">Selecione</option>{flats.map(x=><option key={x.id} value={x.id}>{x.local?.nome} • Flat {x.numero}</option>)}</select></label><label className="text-xs font-semibold md:col-span-2">Modelo<select value={form.modeloContratoId} onChange={e=>set("modeloContratoId",e.target.value)} className="mt-1 w-full p-3 rounded-xl border bg-transparent"><option value="">Modelo padrão</option>{modelos.map(x=><option key={x.id} value={x.id}>{x.titulo}</option>)}</select></label></div>}
      {step===2&&<div className="grid md:grid-cols-3 gap-4"><label className="text-xs font-semibold">Emissão<input type="date" value={form.dataEmissao} onChange={e=>set("dataEmissao",e.target.value)} className="mt-1 w-full p-3 rounded-xl border bg-transparent"/></label><label className="text-xs font-semibold">Unidade<select value={form.tipoValidade} onChange={e=>set("tipoValidade",e.target.value)} className="mt-1 w-full p-3 rounded-xl border bg-transparent"><option>MESES</option><option>DIAS</option></select></label><label className="text-xs font-semibold">Duração<input type="number" min="1" value={form.validadeValor} onChange={e=>set("validadeValor",e.target.value)} className="mt-1 w-full p-3 rounded-xl border bg-transparent"/></label><div className="md:col-span-3 p-4 rounded-xl bg-blue-50 dark:bg-blue-950/30 text-sm font-bold">Término previsto: {dataFinal}</div></div>}
      {step===3&&<div className="grid md:grid-cols-3 gap-4">{[["valorMensal","Valor mensal"],["diaVencimento","Dia vencimento"],["multaAtrasoPercentual","Multa %"],["jurosAtrasoPercentual","Juros %"],["valorCaucao","Caução"],["caucaoParcelas","Parcelas caução"],["multaRescisaoMeses","Multa rescisão (meses)"]].map(([k,l])=><label key={k} className="text-xs font-semibold">{l}<input type="number" step="0.01" value={(form as any)[k]} onChange={e=>set(k,e.target.value)} className="mt-1 w-full p-3 rounded-xl border bg-transparent"/></label>)}<label className="text-xs font-semibold">Forma de pagamento<select value={form.formaPagamento} onChange={e=>set("formaPagamento",e.target.value)} className="mt-1 w-full p-3 rounded-xl border bg-transparent"><option>PIX</option><option>DINHEIRO</option><option>CARTAO</option><option>BOLETO</option></select></label></div>}
      {step===4&&<div className="space-y-5"><div className="grid md:grid-cols-3 gap-3"><div><span className="text-[10px] text-slate-400">LOCATÁRIO</span><p className="font-bold text-sm">{selectedLoc?.nome||"Não selecionado"}</p></div><div><span className="text-[10px] text-slate-400">IMÓVEL</span><p className="font-bold text-sm">{selectedFlat?selectedFlat.local?.nome+" • Flat "+selectedFlat.numero:"Não selecionado"}</p></div><div><span className="text-[10px] text-slate-400">VALOR</span><p className="font-bold text-sm">R$ {Number(form.valorMensal||0).toLocaleString("pt-BR",{minimumFractionDigits:2})}</p></div></div><div className="p-5 rounded-xl border bg-slate-50 dark:bg-slate-950"><div className="flex items-center gap-2 font-bold mb-3"><FileText className="w-4 h-4 text-blue-600"/>Prévia do modelo</div><div className="prose prose-sm dark:prose-invert max-w-none" dangerouslySetInnerHTML={{__html:model?.conteudoHtml||"<p>Modelo padrão do sistema.</p>"}}/></div></div>}
      <div className="flex justify-between mt-6 pt-4 border-t">{step>1?<button onClick={()=>setStep(step-1)} className="px-4 py-2 rounded-xl border text-xs font-bold">Voltar</button>:<span/>}{step<4?<button disabled={step===1&&(!form.locatarioId||!form.flatId)} onClick={()=>setStep(step+1)} className="px-5 py-2 rounded-xl bg-blue-600 text-white text-xs font-bold flex items-center gap-2 disabled:opacity-40">Continuar <ArrowRight className="w-4 h-4"/></button>:<button onClick={submit} disabled={saving||done||!form.valorMensal} className="px-5 py-2 rounded-xl bg-emerald-600 text-white text-xs font-bold flex items-center gap-2 disabled:opacity-40">{done?<><CheckCircle2 className="w-4 h-4"/>Emitido</>:saving?"Emitindo...":"Emitir contrato"}</button>}</div>
    </div>
  </div></Shell>;
}
