"use client";
import React,{useEffect,useMemo,useState} from "react";
import Shell from "@/components/layout/Shell";
import {ArrowDownCircle,ArrowUpCircle,Wallet,AlertTriangle,RefreshCw,ChevronRight} from "lucide-react";

const money=(v:number)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function FinanceiroPage(){
 const [data,setData]=useState<any>({kpis:{},meses:[],receber:[],pagar:[]});const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const r=await fetch("/api/financeiro/fluxo-caixa");const d=await r.json();if(r.ok)setData(d)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const k=data.kpis||{};const max=Math.max(1,...(data.meses||[]).map((m:any)=>Math.max(m.previstoReceber,m.previstoPagar,m.recebido,m.pago)));
 const atrasados=(data.receber||[]).filter((x:any)=>x.status==="ATRASADO").slice(0,8);
 const prox=(data.receber||[]).filter((x:any)=>x.status!=="PAGO").slice(0,8);
 return <Shell><div className="space-y-6">
  <div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase text-blue-600">Fase 4 • Financeiro</p><h1 className="text-2xl font-extrabold">Centro Financeiro</h1><p className="text-sm text-slate-500">Fluxo de caixa, cobranças, pagamentos e inadimplência.</p></div><button onClick={load} className="px-4 py-2 rounded-xl border bg-white dark:bg-slate-900 text-xs font-bold flex items-center gap-2"><RefreshCw className="w-4 h-4"/> Atualizar</button></div>
  {loading?<div className="p-8 text-sm text-slate-500">Carregando financeiro...</div>:<>
  <div className="grid grid-cols-2 lg:grid-cols-6 gap-3">{[
   ["Recebido",money(k.recebimentos),"emerald"],["Pago",money(k.pagamentos),"rose"],["Saldo",money(k.saldo),k.saldo>=0?"blue":"rose"],["A receber",money(k.abertoReceber),"amber"],["A pagar",money(k.abertoPagar),"orange"],["Inadimplente",money(k.inadimplenteReceber),"red"]
  ].map(([l,v,c]:any)=><div key={l} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-4"><span className="text-[10px] font-bold uppercase text-slate-400">{l}</span><p className={`mt-1 text-lg font-extrabold text-${c}-600`}>{v}</p></div>)}</div>
  <div className="grid lg:grid-cols-[1.7fr_1fr] gap-6">
   <section className="bg-white dark:bg-slate-900 border rounded-2xl p-5"><div className="flex items-center justify-between mb-5"><div><h2 className="font-bold">Fluxo dos últimos meses</h2><p className="text-xs text-slate-500">Previsto × realizado</p></div><Wallet className="w-5 h-5 text-blue-600"/></div>
    <div className="space-y-4">{(data.meses||[]).map((m:any)=><div key={m.mes}><div className="flex justify-between text-xs font-bold mb-1"><span>{m.mes}</span><span className={m.saldo>=0?"text-emerald-600":"text-rose-600"}>{money(m.saldo)}</span></div><div className="grid grid-cols-2 gap-2"><div><div className="h-2 rounded-full bg-blue-100 overflow-hidden"><div className="h-full bg-blue-600 rounded-full" style={{width:`${Math.min(100,m.previstoReceber/max*100)}%`}}/></div><span className="text-[10px] text-slate-500">Receber {money(m.recebido)} / {money(m.previstoReceber)}</span></div><div><div className="h-2 rounded-full bg-rose-100 overflow-hidden"><div className="h-full bg-rose-500 rounded-full" style={{width:`${Math.min(100,m.previstoPagar/max*100)}%`}}/></div><span className="text-[10px] text-slate-500">Pagar {money(m.pago)} / {money(m.previstoPagar)}</span></div></div></div>)}</div>
   </section>
   <section className="bg-white dark:bg-slate-900 border rounded-2xl p-5"><div className="flex items-center gap-2 mb-4"><AlertTriangle className="w-5 h-5 text-rose-500"/><h2 className="font-bold">Inadimplência</h2></div>{atrasados.length===0?<p className="text-xs text-slate-500">Nenhuma conta vencida no período.</p>:<div className="space-y-2">{atrasados.map((c:any)=><div key={c.id} className="p-3 rounded-xl bg-rose-50 dark:bg-rose-950/30 border border-rose-100 dark:border-rose-900"><div className="flex justify-between gap-2"><span className="text-xs font-bold">{c.locatario?.nome||"Locatário"}</span><span className="text-xs font-extrabold text-rose-600">{money(c.valor-(c.valorPago||0))}</span></div><p className="text-[10px] text-slate-500">Venc. {new Date(c.dataVencimento).toLocaleDateString("pt-BR")}</p></div>)}</div>}</section>
  </div>
  <div className="grid lg:grid-cols-2 gap-6">
   <section className="bg-white dark:bg-slate-900 border rounded-2xl overflow-hidden"><div className="p-5 border-b flex items-center justify-between"><h2 className="font-bold flex items-center gap-2"><ArrowDownCircle className="w-5 h-5 text-emerald-600"/> Próximos recebimentos</h2><a href="/financeiro/receber" className="text-xs font-bold text-blue-600">Ver contas <ChevronRight className="inline w-3 h-3"/></a></div><div className="divide-y">{prox.slice(0,6).map((c:any)=><div key={c.id} className="p-4 flex justify-between gap-3"><div><p className="text-xs font-bold">{c.locatario?.nome}</p><p className="text-[10px] text-slate-500">Venc. {new Date(c.dataVencimento).toLocaleDateString("pt-BR")} • {c.status}</p></div><span className="text-sm font-extrabold text-emerald-600">{money(Math.max(0,c.valor-(c.valorPago||0)))}</span></div>)}</div></section>
   <section className="bg-white dark:bg-slate-900 border rounded-2xl overflow-hidden"><div className="p-5 border-b flex items-center justify-between"><h2 className="font-bold flex items-center gap-2"><ArrowUpCircle className="w-5 h-5 text-rose-600"/> Contas a pagar</h2><a href="/financeiro/pagar" className="text-xs font-bold text-blue-600">Ver contas <ChevronRight className="inline w-3 h-3"/></a></div><div className="divide-y">{(data.pagar||[]).filter((c:any)=>c.status!=="PAGO").slice(0,6).map((c:any)=><div key={c.id} className="p-4 flex justify-between gap-3"><div><p className="text-xs font-bold">{c.descricao}</p><p className="text-[10px] text-slate-500">Venc. {new Date(c.dataVencimento).toLocaleDateString("pt-BR")} • {c.status}</p></div><span className="text-sm font-extrabold text-rose-600">{money(Math.max(0,c.valor-(c.valorPago||0)))}</span></div>)}</div></section>
  </div></>}
 </div></Shell>
}